=== Adish786/Maintel/mantle-resources/src/main/resources/xsd/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:include schemaLocation="common.xsd"></xs:include>

    <xs:element name="components">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="component" type="componentDefinition" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="componentChildren">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="stylesheet" type="resourceHandle" />
                <xs:element name="script" type="resourceHandle" />
                <xs:element name="svg" type="resourceHandle" />
                <xs:element name="property" type="property" />
                <xs:element name="model" type="model" />
                <xs:element name="map" type="map" />
                <xs:element name="list" type="list" />
                <xs:element name="config" type="config" />
                <xs:element name="message" type="message" />
                <xs:element name="for" type="for" />
                <xs:element name="component" type="component" />
                <xs:element name="component-list" type="component-list" />
                <xs:element name="component-list-item" type="component-list-item" />
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="resourceHandle">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:attribute name="optional" type="xs:boolean"></xs:attribute>
                <xs:attribute name="group" type="xs:string"></xs:attribute>
                <xs:attribute name="evaluated" type="xs:boolean"></xs:attribute>
                <xs:attribute name="path" type="xs:string"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="componentDefinition" mixed="true">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="info" type="info" minOccurs="1" maxOccurs="1" />
                    <xs:group ref="componentChildren" />
                </xs:choice>
                <xs:attribute name="ref" use="optional" type="xs:string" />
                <xs:attribute name="overrides" use="optional" type="xs:string" />
                <xs:attribute name="location" use="optional" type="xs:string" />
                <xs:attribute name="source" use="optional" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Identifier for data source used by component. If this component requires model(s) then source must be set. This will default to same as id if not
                            provided.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="defer" use="optional" type="xs:string" />
                <xs:attribute name="resourcePath" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="component" mixed="true">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:group ref="componentChildren" />
                <xs:attribute name="ref" use="optional" type="xs:string" />
                <xs:attribute name="overrides" use="optional" type="xs:string" />
                <xs:attribute name="location" use="optional" type="xs:string" />
                <xs:attribute name="source" use="optional" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Identifier for data source used by component. If this component requires model(s) then source must be set. This will default to same as id if not
                            provided.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="defer" use="optional" type="xs:string" />
                <xs:attribute name="resourcePath" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="component-list">
       <xs:complexContent>
           <xs:extension base="component">
               <xs:attribute name="iterable" use="required" type="xs:string" />
               <xs:attribute name="modelItemName" use="optional" type="xs:string">
                   <xs:annotation>
                       <xs:documentation>
                           Defaults to "item" if unspecified.
                       </xs:documentation>
                   </xs:annotation>
               </xs:attribute>
           </xs:extension>
       </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="mantleComponentsRequired">
		<xs:restriction base="xs:string">
		  <xs:pattern value="Mantle Components/([a-zA-Z0-9/\s])*"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="info">
        <xs:sequence>
            <xs:element name="category" type="mantleComponentsRequired" minOccurs="1" maxOccurs="1" />
            <xs:element name="displayName" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="previewType" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="documentation" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="tags" type="xs:string" />
                <xs:element name="previewType" type="previewType" />
                <xs:element name="resizable" type="xs:boolean" />
                <xs:element name="bgColor" type="xs:string" />
            </xs:choice>
            <xs:group ref="componentChildren" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="previewType">
       <xs:restriction base="xs:string">
           <xs:enumeration value="default"/>
           <xs:enumeration value="markup"/>
           <xs:enumeration value="none"/>
       </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="for">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:group ref="componentChildren" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/newsletter-signup/newsletter-signup.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/components.xsd">

	<component id="mntl-newsletter-signup" resourcePath="/components/newsletter-signup/views/newsletter-signup.ftl">
		<info>
			<category>Mantle Components/Newsletter</category>
			<displayName>Newsletter Signup</displayName>
			<documentation>
				### Default components

				- **mntl-newsletter-signup__heading**

				Location **header**. Default heading you can customize or override.

				- **mntl-newsletter-submit**

				Location **submit**. Default **pc, tablet** view. Contains input field, hidden **listName**, hidden **customEventName** and hidden **CSRFToken** fields, and submit button.

				Placeholder text and button customizable. __**listName** must be set by vertical.__

				**customEventName** is an optional field to be set by vertical to trigger a Sailthru custom event like "Welcome email series".

				- **mntl-newsletter-one-tap**

				Location **submit**. Default **mobile** view. Simple **a** tag with customizable **attrs.href** and **text**.

				Note that **attrs.href** will be base64 encoded automatically to prevent scrapers from reading the email address in plain text.

				- **mntl-newsletter-signup__success**

				Location **success**. **pc, tablet** view. Default container for success message. Hidden by default, visible on successful submit / when **mntl-newsletter-signup** gets class **is-submit-success**

				- **mntl-newsletter-signup__error**

				Location **error**. **pc, tablet** view. Default container for error message. Hidden by default, visible on submit / when **mntl-newsletter-signup** gets class **is-submit-error**

				###newsletter-signup.js

				Sets callback on form **submit** to serialize form data and perform method on action.

				On success, adds **is-submit-success** class to **mntl-newsletter-signup** and triggers event **submit-success** on **mntl-newsletter-signup**

				On error, adds **is-submit-error** class to **mntl-newsletter-signup** and triggers event **submit-error** on **mntl-newsletter-signup**

				Use the success and error classes to style as you wish. Attach event handlers for **submit-success** and **submit-error** for custom functionality.

				###newsletter-one-tap.js

				Sets click handler on one-tap button to decode **attrs.href** prior to setting **window.location**.
			</documentation>
			<for id="mntl-newsletter-submit">
				<property name="listName" value="healthtips1" />
			</for>
		</info>
		<component location="header" ref="mntl-text-block" id="mntl-newsletter-signup__heading">
			<property name="text" value="Sign up for our Newsletter" />
		</component>
		<component location="submit" ref="mntl-newsletter-submit" views="pc, tablet" />
		<component location="submit" ref="mntl-newsletter-one-tap" views="mobile" />
        <component location="footer" ref="mntl-text-block" id="mntl-newsletter-signup__success" views="pc, tablet">
            <property name="text" value="You're in! Thanks for signing up." />
        </component>
        <component location="footer" ref="mntl-text-block" id="mntl-newsletter-signup__error" views="pc, tablet">
            <property name="text" value="There was an error. Please try again." />
        </component>

		<for id="data-shared-services, mntl-newsletter-one-tap.attrs.href, sharedservices">
			<property name="enableSharedServices" value="${@sharedServicesConfig?.value}" onError="ignore">
				<model id="sharedServicesConfig" name="externalConfig" onError="ignore">
					<property name="key" value="com.about.globe.sharedservices.enabled" />
				</model>
			</property>
		</for>

		<for id="data-newsletter-object-ids">
			<property name="newsletterObjectIds" value="${@newsletterObjectIdsConfig?.value}" onError="ignore">		
				<model id="newsletterObjectIdsConfig" name="externalConfig" onError="ignore">
					<property name="key" value="com.about.globe.sharedservices.newsletterObjectIds" />
				</model>
			</property>
		</for>

		<for id="mntl-newsletter-one-tap.attrs.href">
			<property name="sharedServicesOneTapLink" value="${@sharedServicesOneTapLinkConfig?.value}" onError="ignore">
				<model id="sharedServicesOneTapLinkConfig" name="externalConfig" onError="ignore">
					<property name="key" value="com.about.globe.sharedservices.mobileLink" />
				</model>
			</property>
		</for>
	</component>

	<component id="mntl-newsletter-submit" resourcePath="/components/newsletter-signup/views/submit.ftl">
		<info>
			<category>Mantle Components/Newsletter</category>
			<displayName>Newsletter Submit</displayName>
		</info>

		<stylesheet path="/static/mantle/components/newsletter-signup/newsletter-signup.css"></stylesheet>
		<script path="/static/mantle/components/newsletter-signup/newsletter-signup.js"></script>

		<map name="attrs">
			<property name="data-reg-source-id" value="${@regSourceId}" onError="ignore" />
			<property name="data-newsletter-object-ids" value="${@newsletterObjectIds}" onError="ignore" />
			<property name="data-shared-services" value="${@enableSharedServices}" onError="ignore" />
		</map>

		<property name="placeholderText" value="Enter your email" views="pc, tablet" />
		<property name="placeholderText" value="Enter email" views="mobile" />
		<property name="csrfToken" value="${requestContext.csrfToken}" />
		<property name="sharedservices" value="${@enableSharedServices == 'true'}" onError="ignore" />

		<component location="submitButton" id="mntl-newsletter-submit__button" ref="mntl-button">
			<map name="attrs">
				<property name="type" value="submit" />
			</map>

			<property name="text" value="Sign up" />
		</component>
	</component>

	<component id="mntl-newsletter-one-tap" resourcePath="/components/newsletter-signup/views/newsletter-one-tap.ftl">
		<info>
			<category>Mantle Components/Newsletter</category>
			<displayName>Newsletter One Tap</displayName>
		</info>

		<script path="/static/mantle/components/newsletter-signup/newsletter-one-tap.js"></script>
		<property name="tag" value="a" />
		<map id="attrs">
			<property name="href" value="mailto:replaceme?subject=replaceme" />
			<property name="target" value="_blank" />
		</map>
		<property name="text" value="One Tap Sign Up" />
		<component location="button" ref="mntl-button" id="mntl-newsletter-one-tap__button" />
	</component>
</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/image/universal-image.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/components.xsd">

    <component id="mntl-universal-image" resourcePath="/components/image/view/universal-image.ftl">
        <info>
            <category>Mantle Components/Media</category>
            <displayName>Universal Image</displayName>
            <description>
                This is the converged image component. It replaces the mntl-image component and all other image components created by the verticals. 
                This uses a new thumbor macro with enhanced functionality for internally hosted images, and allows for externally hosted images to be displayed using a plain img tag. 
                The new macro has gifv functionality built in, meaning any image with an extension of .gif will be served as a video in a video tag.
            </description>
            <documentation>
                # Properties

                ## alt
                The text that will be used for the image alt attribute

                ## class
                Used to add any addtional classes to the img tag

                ## externalUrl
                Used to load an externally hosted image. If this is specified then this will override any image supplied in the image property

                ## image
                The image url or object to be loaded and displayed in the img tag

                ## height
                The height of the image you want to load

                ## width
                The width of the image you want to load

                ## role
                Can be used to set the aria role of the image. For example if the image is used as only for design purposes, then you should set the value to "presentation"

                ## tag
                Used to wrap the image in the specified html tag. If value is not specified then the image will not be wrapped. For example if you want to wrap the image in a figure tag, specify "figure"

                ## tagClass
                Class or classes that will be applied to the wrapping element if tag is specified.
                
                ## idPrefix
                Prefix of id that will be added to img tag. Only used for SC Block images for GTM tracking.

                ## fitInStyle
                Used by thumbor to determine the best way to fit an image into the desired dimensions (only used by commerce). More info in the thumbor docs: https://thumbor.readthedocs.io/en/6.7.2/usage.html?highlight=fit-in#fit-in

                ## filters
                List of operations that thumbor will do to your image. This is commonly used to restict the size of images, and to prevent thumbor fromscaling up small images.

                ## expand
                A integer value used by the lazysizes library to determine when to start loading an offscreen image. For example a value of 100 means lazysizes will request the offscreen image when it is within 100px of the viewport.

                ## lazyload
                A boolean value used to determine whether the image should be lazily loaded.

                ## placeholder
                A boolean value used to determine whether the image should be wrapped in a placeholder div. This placeholder is useful when lazily loading images to prevent CLS

                ## placeholderHeight
                The height that the image placeholder should be. This is important when setting specific heights and widths on lazily loaded images.

                ## placeholderWidth
                The width that the image placeholder should be. This is important when setting specific heights and widths on lazily loaded images.

                ## srcset
                An map used to create the srcset url string for the image. The possible keys on the map are minWidth (the smallest width the image could be), maxWidth (the largest width the image could be), 
                maxHeight (the largest height the image could be), and stepCount (used to determine the number of srcset urls generated). These all have integer values, and minWidth, maxWidth, and maxHeight are all integers that represent a pixel value.

                ## sizes
                The string that will be used for the sizes attribute on the image.

                ## imgAttrs
                DO NOT USE!!! Only present for compatibility with sc-block-image and masonry-list. 
                Should only be used to set data-dim-ratio, data-img-lightbox, data-click-tracked, or data-tracking-container. 
                Acts similarly to the attrs map to add extra data- properties to the img tag. 

                # Dependencies/References

                ## gif.js
                This file uses the srcset and sizes to determine the correct size video to load. It then updates the video with the correct src
            </documentation>

            <for id="this, alt, width, height, placeholderWidth, placeholderHeight">
                <property name="image" value="${@document.getImageForUsage('PRIMARY')?.objectId != null ? @document.getImageForUsage('PRIMARY') : null}">
                    <model name="mockDocument" id="document">
                        <property name="template" value="structured-content-basic-one-of-each" />
                    </model>
                </property>
            </for>
            <property name="lazyload" value="false" type="boolean" />
        </info>

        <script path="/static/mantle/components/image/js/gif.js" />
        <stylesheet path="/static/mantle/components/image/css/gif.css" />

        <!-- basic properties -->
        <property name="alt" value="${@image?.alt ?: ''}" />
        <property name="class" value="" />
        <property name="externalUrl" value="" />
        <property name="height" value="${@image?.height ?: 0}" />
        <property name="width" value="${@image?.width ?: 0}" />
        <property name="role" value="" />
        <property name="tag" value="" />
        <property name="tagClass" value="" />
        <property name="idPrefix" value="" />

        <!-- thumbor related properties -->
        <property name="fitInStyle" value="" />
        <list id="filters">
            <property name="upscale" value="${imageFilter.noUpscale()}" />
            <!-- the maxBytes filter is here to ensure that the requested image size does not exceed 150kb and does not impact resource loading and SEO. 
                if you are going to override the default value and increase the maxmium size the image can be, please check with the SEO team first!!! -->
            <property name="maxBytes" value="max_bytes(150000)" />
            <property name="stripicc" value="strip_icc()" />
        </list>

        <!-- lightbox related properties -->
        <property name="useHiResLightbox" value="false" type="boolean" />
        <property name="hiResLightboxWidth" value="0" type="integer" />

        <!-- lazyloading and responsive image properties -->
        <property name="expand" value="0" type="integer" />
        <property name="lazyload" value="true" type="boolean" />
        <property name="placeholder" value="true" type="boolean" />
        <property name="placeholderHeight" value="${@image?.height ?: 0}" />
        <property name="placeholderWidth" value="${@image?.width ?: 0}" />
        <map id="srcset">
            <property name="minWidth" value="700" type="integer" />
            <property name="maxWidth" value="300" type="integer" />
            <property name="maxHeight" value="0" type="integer" />
            <property name="stepCount" value="3" type="integer" />
        </map>
        <property name="sizes" value="" />

        <property name="image" value="${messages['defaultPlaceHolderImage'] ?: ''}" />

        <!-- DO NOT USE unless image is in masonry-list or sc-block-image components. property that is needed for backwards compatibility. 
            Should only be used to set data-dim-ratio, data-img-lightbox, data-click-tracked, or data-tracking-container! -->
        <map id="imgAttrs" />

    </component>

</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/base/group.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/components.xsd">

	<component id="mntl-group" resourcePath="/components/base/view/group.ftl">
        <info>
            <category>Mantle Components/Base</category>
            <displayName>Group</displayName>
            <description>
                Basic wrapper that provides "content" location hook for child components.  Same as Mantle Block component but does not provide a wrapper element.
            </description>
            <documentation>
                # Locations

                * __content__
            </documentation>
            <tags>Complete</tags>
            <previewType>none</previewType>
        </info>
    </component>

	<component id="mntl-block" resourcePath="/components/base/view/block-group.ftl">
        <info>
            <category>Mantle Components/Base</category>
            <displayName>Mantle Block</displayName>
            <description>
                Outputs wrapper element for component and provides "content" location hook for child components.  Same as the Mantle Group component, but provides a wrapper element.
            </description>
            <documentation>
                # Properties / Models

                * __tag__: tag used for the wrapper element.  Defaults to `div`.

                # Locations

                * __content__
            </documentation>
            <tags>Complete</tags>
            <previewType>none</previewType>
        </info>
    </component>

	<component id="mntl-expandable-block" resourcePath="/components/base/view/expandable-block.ftl">
        <info>
            <category>Mantle Components/Base</category>
            <displayName>Mantle Expandable Block</displayName>
            <description>
                Outputs wrapper element for component and provides "static-content", "toggle-content" and "expandable-content" location hooks for child components.
                Components placed in "static-content" location are always shown.
                Components placed in "expandable-content" location are shown/hidden on click of any component in "toggle-content" location.
            </description>
            <documentation>
                Add the class name `is-expanded` to show the components in the "expandable-content" location by default.
                Otherwise the components in the "expandable-content" location are hidden by default.
            </documentation>
            <tags>Complete</tags>
            <previewType>none</previewType>
        </info>
        <script path="/static/mantle/components/base/js/expandable-block.js" />
        <stylesheet path="/static/mantle/components/base/css/expandable-block.css" />
    </component>

	<component id="mntl-text-block" resourcePath="/components/base/view/text-block.ftl">
        <info>
            <category>Mantle Components/Base</category>
            <displayName>Text Block</displayName>
            <description>
                Outputs wrapper div for component and sets content to configured text
            </description>
            <documentation>
                __text__ ```String```

                Text to be displayed in component
            </documentation>
            <tags>Complete</tags>
            <previewType>none</previewType>
            
            <property name="text" value="Sample text" />
        </info>
    </component>

    <component id="mntl-text-link" resourcePath="/components/base/view/text-link.ftl">
        <info>
            <category>Mantle Components/Base</category>
            <displayName>Text Link</displayName>
            <description>
                Outputs wrapper link component and sets content to configured text. 
                If no uri property is passed in, component will default to a passed in tag or (if not tag is passed in) defaults to span instead.
            </description>
            <documentation>
                __model.text__ ```String```

                Text to be displayed as link

                __model.uri__ ```String```

                URI where link goes

                __model.external__ ```boolean|false``` [optional]

                If true, will make target='_blank'

                __model.trackingContainer__ ```boolean|true``` [optional]

                Will add or remove tracking from component
            </documentation>
            <tags>Complete</tags>
            <previewType>none</previewType>
            
            <property name="text" value="Sample text" />
        </info>
    </component>
    
    <component id="mntl-image" resourcePath="/components/base/view/image.ftl">
        <info>
            <category>Mantle Components/Base</category>
            <displayName>Image</displayName>
            <description>
                Image
            </description>
            <documentation>
            </documentation>
            <tags>Complete</tags>
        	<property name="imageObjectId" value="about-us-mrb-5b7efad9c9e77c0024cee5a1.png" />
            <property name="alt" value="This is a test alt text with &quot;quotations&quot; in it."  />
            <property name="width" value="752" type="integer" />
		    <property name="height" value="160" type="integer" />	            
        </info>
    </component>

</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/recipe/lrs-ingredients/lrs-ingredients.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/components.xsd">

    <component id="mntl-lrs-ingredients" ref="mntl-block">
        <info>
            <category>Mantle Components/Recipe</category>
            <displayName>Mantle LRS Ingredients</displayName>
            <description>
                Local Retailer Scroller: Displays Structured Ingredients for Carbonized Recipe SC Templates with ad units
                such as Branded Ingredient Units (BIU), May We Suggest, (MWS), and Local Offers
            </description>
            <documentation>
                ### Note

                - When using this component, you should for-target your `mntl-preconnect.domains` with the necessary subdomains
                in the template which you're using this component.

                ### Properties

                - __useLRS__ **boolean**

                Adds a data attribute for each ingredient for the LRS script based on meredithId field, default to true

                - __data-vertical__ **string**

                Vertical initial (such as fw for food and wine) to be prefixed to call for appropriate calvera script,
                default is empty string to throw Javascript Error.

                - __data-load-offset__ **string**

                How many pixels the LRS component is offscreen to start loading the LRS script. This should act as a middle ground with deferring,
                while still fetching the ad script earlier to help with ad impression performance. Default to 300px.
                On the vertical side this will be overridden and powered by a proctor test on launch.
            </documentation>

            <for id="list">
                <model name="mockDocument" id="document">
                    <property name="template" value="carbonized-recipe-sc" />
                </model>
            </for>

            <map id="attrs">
                <property name="data-vertical-prefix" value="fw" />
            </map>
        </info>

        <stylesheet path="/static/mantle/components/recipe/lrs-ingredients/lrs-ingredients.css" />
        <script path="/static/mantle/components/recipe/lrs-ingredients/lrs-ingredients.js" />

        <map id="attrs">
            <property name="data-vertical-prefix" value="" />
            <property name="data-load-offset" value="300" />
        </map>

        <component location="content" ref="mntl-structured-ingredients">
            <property name="useLRS" value="true" type="boolean" />
        </component>

    </component>

</components>
