=== Adish786/Maintel/mantle-resources/src/main/resources/xsd/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:include schemaLocation="common.xsd"></xs:include>

    <xs:element name="components">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="component" type="componentDefinition" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="componentChildren">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="stylesheet" type="resourceHandle" />
                <xs:element name="script" type="resourceHandle" />
                <xs:element name="svg" type="resourceHandle" />
                <xs:element name="property" type="property" />
                <xs:element name="model" type="model" />
                <xs:element name="map" type="map" />
                <xs:element name="list" type="list" />
                <xs:element name="config" type="config" />
                <xs:element name="message" type="message" />
                <xs:element name="for" type="for" />
                <xs:element name="component" type="component" />
                <xs:element name="component-list" type="component-list" />
                <xs:element name="component-list-item" type="component-list-item" />
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="resourceHandle">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:attribute name="optional" type="xs:boolean"></xs:attribute>
                <xs:attribute name="group" type="xs:string"></xs:attribute>
                <xs:attribute name="evaluated" type="xs:boolean"></xs:attribute>
                <xs:attribute name="path" type="xs:string"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="componentDefinition" mixed="true">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="info" type="info" minOccurs="1" maxOccurs="1" />
                    <xs:group ref="componentChildren" />
                </xs:choice>
                <xs:attribute name="ref" use="optional" type="xs:string" />
                <xs:attribute name="overrides" use="optional" type="xs:string" />
                <xs:attribute name="location" use="optional" type="xs:string" />
                <xs:attribute name="source" use="optional" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Identifier for data source used by component. If this component requires model(s) then source must be set. This will default to same as id if not
                            provided.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="defer" use="optional" type="xs:string" />
                <xs:attribute name="resourcePath" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="component" mixed="true">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:group ref="componentChildren" />
                <xs:attribute name="ref" use="optional" type="xs:string" />
                <xs:attribute name="overrides" use="optional" type="xs:string" />
                <xs:attribute name="location" use="optional" type="xs:string" />
                <xs:attribute name="source" use="optional" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Identifier for data source used by component. If this component requires model(s) then source must be set. This will default to same as id if not
                            provided.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="defer" use="optional" type="xs:string" />
                <xs:attribute name="resourcePath" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="component-list">
       <xs:complexContent>
           <xs:extension base="component">
               <xs:attribute name="iterable" use="required" type="xs:string" />
               <xs:attribute name="modelItemName" use="optional" type="xs:string">
                   <xs:annotation>
                       <xs:documentation>
                           Defaults to "item" if unspecified.
                       </xs:documentation>
                   </xs:annotation>
               </xs:attribute>
           </xs:extension>
       </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="mantleComponentsRequired">
		<xs:restriction base="xs:string">
		  <xs:pattern value="Mantle Components/([a-zA-Z0-9/\s])*"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="info">
        <xs:sequence>
            <xs:element name="category" type="mantleComponentsRequired" minOccurs="1" maxOccurs="1" />
            <xs:element name="displayName" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="previewType" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="documentation" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="tags" type="xs:string" />
                <xs:element name="previewType" type="previewType" />
                <xs:element name="resizable" type="xs:boolean" />
                <xs:element name="bgColor" type="xs:string" />
            </xs:choice>
            <xs:group ref="componentChildren" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="previewType">
       <xs:restriction base="xs:string">
           <xs:enumeration value="default"/>
           <xs:enumeration value="markup"/>
           <xs:enumeration value="none"/>
       </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="for">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:group ref="componentChildren" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/taxonomysc/taxonomysc.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/components.xsd">
    <component id="mntl-taxonomysc" resourcePath="/components/taxonomysc/view/taxonomysc.ftl">
        <info>
            <category>Mantle Components/TaxonomySC</category>
            <displayName>TaxonomySC Base</displayName>
            <description>Base component to be used for rendering the TAXONOMYSC template type.</description>
            <previewType>none</previewType>
        </info>
        <stylesheet path="/static/mantle/components/taxonomysc/css/taxonomysc.css" />

        <component location="header" ref="mntl-taxonomysc-header" />

        <component location="structuredContent" id="mntl-taxonomysc-content" ref="mntl-sc-page">
            <for id="mntl-sc-page-contents.contents">
                <property name="blockList" value="${@document.contents.list}" mode="replace">
                    <model name="DOCUMENT" id="document" />
                </property>
                <property name="adInsertionStrategyName" value="noAdsStructuredContentAdInsertionStrategy" />
            </for>
        </component>

        <component location="fixedContent" ref="mntl-document-spotlight">
            <for id="mntl-card-list-items, mntl-card-list__button.arbitraryDependency">
                <model id="listItems" name="documentTaxeneList" mode="replace">
                    <model id="documentList" name="filterArticles">
                        <model id="articles" name="descendantArticles" />
                        <model id="articlesToFilterOut" name="documentsReferencedByContentBlocks">
                            <model name="DOCUMENT" id="document" />
                        </model>
                    </model>
                </model>
            </for>
        </component>

        <!-- Intended for verticals to mode replace with their own newsletter component -->
        <component location="fixedContent" id="mntl-taxonomysc-newletter" ref="mntl-group" />
        <component location="fixedContent" ref="mntl-taxonomysc-child-nodes" />
        <component location="fixedContent" ref="mntl-taxonomysc-article-list-group" />

        <component id="mntl-taxonomysc-child-list" ref="mntl-taxonomysc-child-article-list" />

        <component location="fixedContent" ref="mntl-taxonomysc-child-block" />

        <component location="fixedContent" ref="mntl-taxonomysc-sibling-nodes" />

        <component location="fixedContent" id="mntl-taxonomysc-sources" ref="mntl-article-sources">
            <for id="mntl-article-sources__heading">
                <property name="text" value="Page Sources" />
            </for>
        </component>

        <!-- Though `mntl-document-spotlight` only needs a small amount of articles (~24) we are changing the limit here because that means globe will only do one call instead of two -->
        <for id="mntl-document-spotlight.mntl-card-list-items.listItems.documentList.articles, 
        mntl-document-spotlight.mntl-card-list__button.arbitraryDependency.listItems.documentList.articles,
        mntl-taxonomysc-child-list.mntl-card-list-items.listItems.documentList.articles,
        mntl-taxonomysc-child-list.mntl-card-list__button.arbitraryDependency.listItems.documentList.articles,
        mntl-taxonomysc-child-list.mntl-card-list-items.listItems.documentList,
        mntl-taxonomysc-child-list.mntl-card-list-items.mntl-card-list__button.arbitraryDependency.documentList,
        mntl-taxonomysc-article-list-group.mntl-taxonomysc-article-list.mntl-card-list-items.listItems.documentList.articles,
        mntl-taxonomysc-article-list-group.mntl-taxonomysc-article-list.mntl-card-list__button.arbitraryDependency.listItems.documentList.articles
        ">
            <property name="relationships" value="primaryParent,secondaryParent" />
            <property name="limit" value="500" type="integer" />
        </for>

    </component>
</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/image/gif.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/components.xsd">

    <component id="mntl-gif" resourcePath="/components/image/view/gif.ftl">
        <info>
            <category>Mantle Components/Media</category>
            <displayName>Gif</displayName>
            <description>
                This displays a gif as a video in an html video tag. This works by using thumbor to convert the gif into a webm or mp4 video and setting that as the source of the video tag. These videos will always be lazily loaded.
            </description>
            <documentation>
                # Classes

                ## __.video__
                Class on video tag

                # Properties

                ## class
                Text that will be added to the class attribute on the video tag

                ## image
                The image object of the gif

                ## objectId
                The image objectId of the gif (this is used as a fallback if the full image object is not available)

                ## width
                Width of the gif

                ## height
                Height of the gif

                ## alt
                The alt txt for image which will be used to create an aria-description property on the video

                ## placeholder
                Whether to wrap the video in a placeholder to prevent CLS

                ## placeholderHeight
                The height that the image placeholder should be. This is important when setting specific heights and widths on lazily loaded images.

                ## placeholderWidth
                The width that the image placeholder should be. This is important when setting specific heights and widths on lazily loaded images.

                ## srcset
                The srcset that will be used with the sizes to determing the correct size of video to use. Must specify sizes if this is used
                
                ## sizes
                The sizes that will be used with the srcset to determine the correct size of video to use. Must be specified if srcset is used. It is preferred that px or vw units be used to get the best performance. If a css calc function is used there is fallback code in place, but may result in worse performance.

                # Dependencies/References

                ## gif.js
                This file uses the srcset and sizes to determine the correct size video to load. It then updates the video with the correct src
            </documentation>

            <for id="this, alt, width, height, placeholderWidth, placeholderHeight">
                <property name="image" value="${@document.getImageForUsage('PRIMARY')?.objectId != null ? @document.getImageForUsage('PRIMARY') : null}">
                    <model name="mockDocument" id="document" mode="replace">
                        <property name="template" value="structured-content-single-basic-gif" />
                    </model>
                </property>
            </for>

        </info>

        <script path="/static/mantle/components/image/js/gif.js"></script>
        <stylesheet path="/static/mantle/components/image/css/gif.css"></stylesheet>
        
        <!-- basic properties -->
        <property name="class" value="mntl-gif" />
        <property name="alt" value="${@image != null AND @image.alt != null ? @image.alt : ''}" />
        <property name="height" value="${@image != null ? @image.height : 0}" />
        <property name="width" value="${@image != null ? @image.width : 0}" />

        <!-- thumbor related properties -->
        <property name="fitInStyle" value="" />

        <!-- lazyloading and responsive image properties -->
        <property name="placeholder" value="true" type="boolean" />
        <property name="placeholderHeight" value="${@image != null ? @image.height : 0}" />
        <property name="placeholderWidth" value="${@image != null ? @image.width : 0}" />
        <map id="srcset">
            <property name="minWidth" value="700" type="integer" />
            <property name="maxWidth" value="300" type="integer" />
            <property name="maxHeight" value="0" type="integer" />
            <property name="stepCount" value="3" type="integer" />
        </map>
        <property name="sizes" value="(max-width: 768px) 300px, 700px" />
        
        <for id="this, alt, width, height, placeholderHeight, placeholderWidth">
            <property name="image" value="${@document != null ? @document.getImageForUsage('PRIMARY') : null}" onError="ignore">
                <model name="DOCUMENT" id="document">
                    <property name="url" value="${messages['defaultImageUrl']}" />
                </model>
            </property>
        </for>
    </component>

</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/auth0/auth0.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/components.xsd">
    <component id="mntl-auth0" resourcePath="/components/auth0/auth0.ftl">
        <info>
            <category>Mantle Components/Auth</category>
            <displayName>Auth0</displayName>
            <description>Integrate with auth0 for authentication</description>
            <documentation />
        </info>
        <stylesheet path="/static/mantle/components/auth0/auth0.css" />
        <script group="top" path="/static/mantle/components/auth0/auth0Constants.js" />
        <script path="/static/mantle/components/auth0/auth0.js" />
        
        <map id="attrs">
            <property name="data-auth0-enabled" value="${@externalConfigName.value}" onError="ignore">
                <model name="externalConfig" id="externalConfigName">
                    <property name="key" value="com.about.globe.auth0.enabled" />
                    <property name="default" value="false" />
                </model>
            </property>
            <property name="data-auth0-domain" value="${@externalConfigName.value}" onError="ignore">
                <model name="externalConfig" id="externalConfigName">
                    <property name="key" value="com.about.globe.auth0.domain" />
                </model>
            </property>
            <property name="data-auth0-client-id" value="${@externalConfigName.value}" onError="ignore">
                <model name="externalConfig" id="externalConfigName">
                    <property name="key" value="com.about.globe.auth0.clientId" />
                </model>
            </property>
            <property name="data-auth0-audience" value="${@externalConfigName.value}" onError="ignore">
                <model name="externalConfig" id="externalConfigName">
                    <property name="key" value="com.about.globe.auth0.audience" />
                </model>
            </property>
            <property name="data-auth0-type" value="signin" />
        </map>
        <property name="logoutUrl" value="/auth0/logout"/>
        <property name="cta" value="Log In"/>
    </component>

    <component id="mntl-auth0-sign-out" ref="mntl-auth0">
        <map id="attrs">
            <property name="data-auth0-type" value="signout" />
        </map>
        <property name="cta" value="Log Out"/>
    </component>
</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/quiz/quiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/components.xsd">

    <component id="mntl-disclaimer" resourcePath="/components/quiz/disclaimer.ftl">
        <info>
            <category>Mantle Components/Quizzes</category>
            <displayName>Disclaimer</displayName>
            <description>Add disclaimer</description>
            <documentation></documentation>
            <tags>Complete</tags>
            <resizable>true</resizable>
        </info>
        <property name="disclaimer" value="Disclaimer copy goes here" />
    </component>

	<component id="mntl-quiz-questions" resourcePath="/components/quiz/questions.ftl">
        <info>
            <category>Mantle Components/Quizzes</category>
            <displayName>Questions</displayName>
            <description>Displays questions and answers</description>
            <documentation></documentation>
            <tags>Complete</tags>
            <resizable>true</resizable>
            <!-- Actually needs mock document -->
            <model name="mockDocument" id="document" mode="replace">
                <property name="template" value="pattern-library/quiz" />
            </model>
        </info>

		<stylesheet path="/static/mantle/components/quiz/questions.css" />
        <svg id="quiz-icon-check" path="/static/mantle/svg/quiz-icon-check.svg" />
        <svg id="quiz-icon-x" path="/static/mantle/svg/quiz-icon-x.svg" />

		<model id="document" name="DOCUMENT" />
		<property name="questionImageWidth" value="768" type="integer" />
		<property name="questionImageHeight" value="300" type="integer" />
		<property name="answerImageWidth" value="200" type="integer" />
		<property name="answerImageHeight" value="200" type="integer" />
        <property name="questionHeadingTag" value="span" />
        <property name="revealHeadingTag" value="span" />

        <component id="quiz-icon-check" location="checkbox" ref="mntl-svg">
            <!-- TODO: Convert casing to kebab case in 3.14 -->
            <list id="class">
				<property name="quizicon" value="quizicon" />
                <property name="quizicon-check" value="quizicon-check" />
			</list>

            <property name="name" value="quiz-icon-check" />
        </component>

        <component id="quiz-icon-x" location="checkbox" ref="mntl-svg">
            <!-- TODO: Convert casing to kebab case in 3.14 -->
            <list id="class">
				<property name="quizicon" value="quizicon" />
                <property name="quizicon-check" value="quizicon-x" />
			</list>

            <property name="name" value="quiz-icon-x" />
        </component>
	</component>

	<component id="mntl-quiz-results" resourcePath="/components/quiz/results.ftl">
        <info>
            <category>Mantle Components/Quizzes</category>
            <displayName>Results</displayName>
            <description>Display quiz results</description>
            <documentation>
Display quiz results by looping over `model.document.results.list`. Uses
`model.document.resultsCalc == "BEST_FIT" || model.document.resultsCalc == "PERCENT_CORRECT"`
to modify display.
            </documentation>
            <tags>Complete</tags>
            <resizable>true</resizable>

            <!-- Actually needs mock document since it refs mntl-disclaimer -->
            <for id="this, quizShare">
                <model name="mockDocument" id="document" mode="replace">
                    <property name="template" value="pattern-library/quiz" />
                </model>
            </for>
        </info>
		<stylesheet path="/static/mantle/components/quiz/results.css" />

		<for id="this, quizShare">
			<model id="document" name="DOCUMENT" />
		</for>
		<property name="quizShare" value="${@document.getResultsCalc().name() == 'PERCENT_CORRECT' ? 'I got PERCENTAGE correct.' : 'I got' }" />
        <component location="disclaimer" ref="mntl-disclaimer" />
		<property name="imageWidth" value="768" type="integer" />
        <property name="headingTag" value="span" />
        <property name="resultHeadingTag" value="span" />
        <property name="shareHeadingTag" value="span" />
	</component>

    <component id="mntl-quiz-content" ref="mntl-text-block">
        <property name="text" value="${@document.content}" onError="collapseSilent">
            <model id="document" name="DOCUMENT" />
        </property>
    </component>

	<component id="mntl-quiz" resourcePath="/components/quiz/quiz.ftl">
        <info>
            <category>Mantle Components/Quizzes</category>
            <displayName>Quiz</displayName>
            <description></description>
            <documentation>
                ### quiz.ftl

                * Adds quiz content and wrapper data atribute **data_results_calc**

                ### quiz.js

                * Uses **Mntl.utilities.readyAndDeferred** to initialize quiz script.
            </documentation>
            <tags>Complete</tags>
            <resizable>true</resizable>
            <!-- Actually needs mock document for various dependencies -->
            <for id="c*, c*.p*">
                <model name="mockDocument" id="document" mode="replace">
                    <property name="template" value="pattern-library/quiz" />
                </model>
            </for>
        </info>
        <script group="bottom" path="/static/mantle/static/libs/js/jquery.js" />
        <script group="bottom" path="/static/mantle/js/utilities-built-with-jquery.js" />
		<script group="bottom" path="/static/mantle/components/quiz/quiz.js" />

		<model id="document" name="DOCUMENT" onError="halt" />
        <component location="content" ref="mntl-quiz-content" />
        <component location="content" ref="mntl-quiz-questions" />
        <component location="content" ref="mntl-quiz-results" />
	</component>

</components>
