=== Adish786/Maintel/mantle-resources/src/main/resources/xsd/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:include schemaLocation="common.xsd"></xs:include>

    <xs:element name="components">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="component" type="componentDefinition" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="componentChildren">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="stylesheet" type="resourceHandle" />
                <xs:element name="script" type="resourceHandle" />
                <xs:element name="svg" type="resourceHandle" />
                <xs:element name="property" type="property" />
                <xs:element name="model" type="model" />
                <xs:element name="map" type="map" />
                <xs:element name="list" type="list" />
                <xs:element name="config" type="config" />
                <xs:element name="message" type="message" />
                <xs:element name="for" type="for" />
                <xs:element name="component" type="component" />
                <xs:element name="component-list" type="component-list" />
                <xs:element name="component-list-item" type="component-list-item" />
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="resourceHandle">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:attribute name="optional" type="xs:boolean"></xs:attribute>
                <xs:attribute name="group" type="xs:string"></xs:attribute>
                <xs:attribute name="evaluated" type="xs:boolean"></xs:attribute>
                <xs:attribute name="path" type="xs:string"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="componentDefinition" mixed="true">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="info" type="info" minOccurs="1" maxOccurs="1" />
                    <xs:group ref="componentChildren" />
                </xs:choice>
                <xs:attribute name="ref" use="optional" type="xs:string" />
                <xs:attribute name="overrides" use="optional" type="xs:string" />
                <xs:attribute name="location" use="optional" type="xs:string" />
                <xs:attribute name="source" use="optional" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Identifier for data source used by component. If this component requires model(s) then source must be set. This will default to same as id if not
                            provided.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="defer" use="optional" type="xs:string" />
                <xs:attribute name="resourcePath" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="component" mixed="true">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:group ref="componentChildren" />
                <xs:attribute name="ref" use="optional" type="xs:string" />
                <xs:attribute name="overrides" use="optional" type="xs:string" />
                <xs:attribute name="location" use="optional" type="xs:string" />
                <xs:attribute name="source" use="optional" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Identifier for data source used by component. If this component requires model(s) then source must be set. This will default to same as id if not
                            provided.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="defer" use="optional" type="xs:string" />
                <xs:attribute name="resourcePath" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="component-list">
       <xs:complexContent>
           <xs:extension base="component">
               <xs:attribute name="iterable" use="required" type="xs:string" />
               <xs:attribute name="modelItemName" use="optional" type="xs:string">
                   <xs:annotation>
                       <xs:documentation>
                           Defaults to "item" if unspecified.
                       </xs:documentation>
                   </xs:annotation>
               </xs:attribute>
           </xs:extension>
       </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="mantleComponentsRequired">
		<xs:restriction base="xs:string">
		  <xs:pattern value="Mantle Components/([a-zA-Z0-9/\s])*"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="info">
        <xs:sequence>
            <xs:element name="category" type="mantleComponentsRequired" minOccurs="1" maxOccurs="1" />
            <xs:element name="displayName" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="previewType" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="documentation" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="tags" type="xs:string" />
                <xs:element name="previewType" type="previewType" />
                <xs:element name="resizable" type="xs:boolean" />
                <xs:element name="bgColor" type="xs:string" />
            </xs:choice>
            <xs:group ref="componentChildren" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="previewType">
       <xs:restriction base="xs:string">
           <xs:enumeration value="default"/>
           <xs:enumeration value="markup"/>
           <xs:enumeration value="none"/>
       </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="for">
        <xs:complexContent>
            <xs:extension base="filterable">
                <xs:group ref="componentChildren" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/digital-issue/di-cover-story/di-cover-story.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/components.xsd">

    <component id="mntl-di-cover-story" resourcePath="/components/digital-issue/di-cover-story/di-cover-story.ftl">
        <info>
            <category>Mantle Components/Digital Issue</category>
            <displayName>Cover Story</displayName>
            <description></description>
            <documentation>
                # SUPPORTED BOVD PROPERTIES
                - "background-color": set a flat color for the background (Ex: "#000000")
                - "cta-text-color": set a flat color for the content background (Ex: "#FFFFFF")
                - "cta-background-color": set an image for the background, which will override a color (Ex: "tistheseason_bkd-6f32c18b5ff6480fb22362da1da67387.jpg")
                - "section-title-display": set a color for the content text (Ex: "#000000")

                # REQUIRED PROPERTIES/COMPONENTS

                ## digitalIssueCssVariables
                The map of css variables to apply to the letter from the editor component, pulling from the root config list in the BOVD

                ## digitalIssueRootConfigs
                Pulls from the root config list in the BOVD

                # OPTIONAL PROPERTIES/COMPONENTS

                ## titleClass
                The class for the title
                Default: "type--unicorn"

                ## contentClass
                The class for the content
                Default: "type--dog"
            </documentation>

            <for id="journeySection">
                <property name="index" value="0" type="integer" />
            </for>
        </info>

        <stylesheet path="/static/mantle/components/digital-issue/di-cover-story/di-cover-story.css" />

        <map id="digitalIssueCssVariables">
            <property name="background-color" value="${@digitalIssueSectionConfigs?.get('background-color')}" onError="ignore" />
            <property name="section-title-display" value="${@digitalIssueSectionConfigs?.get('section-title-display')}" onError="ignore" />
            <property name="cta-text-color" value="${@digitalIssueSectionConfigs?.get('cta-text-color')}" onError="ignore" />
            <property name="cta-background-color" value="${@digitalIssueSectionConfigs?.get('cta-background-color')}" onError="ignore" />
        </map>

        <property name="title" value="${@digitalIssueSectionConfigs?.get('section-title-display') == false ? null : @journeySection.shortHeading}" onError="ignore" />

        <component location="background" id="mntl-di-cover-story__background" ref="mntl-universal-image">
            <property name="tag" value="div" />
            <property name="role" value="presentation" />
            <property name="image" value="${@imageConfig != null ? {'objectId': @imageConfig} : null}" onError="ignore">
                <property name="imageConfig" value="${@digitalIssueSectionConfigs?.get('background-image')}" onError="ignore" />
            </property>

            <property name="width" value="1500" type="integer" views="mobile" />
            <property name="width" value="2000" type="integer" views="tablet, pc" />
            <property name="height" value="0" type="integer" />
        </component>

        <component location="anchor" id="mntl-di-module__anchor" ref="mntl-toc-anchor">
            <property name="tocId" value="${T(com.about.mantle.model.tasks.TableOfContentsTask).generateAnchorId(@journeySection.shortHeading)}" />
        </component>

        <component location="card" id="di-cover-story__card" ref="mntl-document-card">
            <property name="trackingContainer" value="true" type="boolean" />

            <property name="title" value="${@document.heading}" onError="ignore" />
            <property name="image" mode="remove" />
            <property name="byline" mode="remove" />
            <property name="cta" mode="remove" />
            <property name="kicker" mode="remove" />

            <property name="titleTextClass" value="type--zebra" />

            <component location="card__top" id="card__media" ref="mntl-universal-image">
                <property name="videoDependency" value="${@landingPageVideo == null ? true : null}" onError="collapseSilent" />

                <property name="placeholderWidth" mode="remove" />
                <property name="placeholderHeight" mode="remove" />
                <property name="tag" value="div" />
                <property name="tagClass" value="card__media" />

                <property name="width" value="840" type="integer" views="mobile, tablet" />
                <property name="height" value="1080" type="integer" views="mobile, tablet" />

                <property name="width" value="1020" type="integer" views="pc" />
                <property name="height" value="1360" type="integer" views="pc" />

                <property name="placeholder" value="true" type="boolean" />
            </component>

            <component location="card__top" ref="mntl-bcplayer">
                <property name="videoDependency" value="${@landingPageVideo != null ? true : null}" onError="collapseSilent" />

                <list id="class">
                    <property name="u-autoplay-looped" value="u-autoplay-looped" />
                </list>

                <map id="attrs">
                    <property name="style" value="--aspectRatioPaddingBottom: ${renderUtils.getVideoContainerPaddingBottomFromUrl(@videoDocument.thumbnailUrl)}; --backgroundImage: url('${@videoDocument.thumbnailUrl}'" onError="collapseSilent" />
                </map>

                <for id="style, accountId, videoId, nativePlayer, videoMetadata, thumbnailUrl">
                    <property name="videoDocument" value="${@landingPageDocument?.primaryVideo?.document}" >
                        <model id="landingPageDocument" name="DOCUMENT" />
                    </property>
                </for>
            </component>

            <component location="content" id="cover-story__text-container" ref="mntl-block">
                <component location="content" id="cover-story__content" ref="mntl-sc-block-html">
                    <list id="class">
                        <property name="mntl-sc-block-html-sliced" mode="remove" />
                        <property name="contentClass" value="type--dog" />
                    </list>

                    <property name="tag" value="div" />
                    <property name="html" value="${@htmlContent}" onError="collapseSilent">
                        <property name="htmlContent" value="${@coverStoryFirstBlock?.data?.html}" onError="collapseSilent" />
                    </property>
                </component>

                <component id="cover-story__read-more" location="content" ref="mntl-button">
                    <property name="text" value="READ MORE" />

                    <list id="class">
                        <property name="class" value="type--squirrel" />
                    </list>
                </component>
            </component>

            <for id="card__media, alt">
                <property name="image" value="${@imageToUse?.objectId != null ? @imageToUse : @imageFallback}">
                    <property name="imageToUse" value="${@document?.getImageForUsage('PRIMARY')}" onError="ignore" views="mobile, tablet" />
                    <property name="imageToUse" value="${utils.isCuratedDocument(@document) ? @document?.programmingImage : @document?.getImageForUsage('PRIMARY')}" onError="ignore" views="pc" />

                    <property name="imageFallback" value="${{objectId: messages['defaultPlaceHolderImage'], alt:'Card Placeholder Image', width: 600, height: 400}}" />
                </property>
            </for>

            <for id="title, url, docId, imageToUse, videoDocument">
                <property name="document" value="${@item.document}" />
            </for>

            <for id="card__media.videoDependency, mntl-bcplayer.videoDependency">
                <property name="landingPageVideo" value="${@landingPageDocument?.primaryVideo?.document}">
                    <model id="landingPageDocument" name="DOCUMENT" />
                </property>
            </for>
        </component>

        <for id="htmlContent">
            <property name="coverStoryFirstBlock" value="${@coverStoryDocument?.getContentsListOfType('HTML')[0]}" onError="ignore" />
        </for>

        <for id="uri, coverStoryFirstBlock">
            <model id="coverStoryDocument" name="DOCUMENT">
                <property name="url" value="${@item?.document?.url}" onError="collapseSilent" />
            </model>
        </for>

        <for id="url, text, document, coverStoryDocument.url">
            <property name="item" value="${@journeySection.journeyDocuments[0]}" />
        </for>

        <for id="item, title, tocId">
            <property name="journeySection" value="${@journeyStructure.sections[@index]}">
                <model name="journeyStructure" />
            </property>
        </for>

        <for id="digitalIssueCssVariables.p*, mntl-di-cover-story__background.image.imageConfig, title">
            <model name="digitalIssueSectionConfigs" />
        </for>

        <for id="journeySection, digitalIssueSectionConfigs">
            <property name="index" value="0" type="integer" />
        </for>
    </component>

</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/widgets/affiliate-disclosure/affiliate-disclosure.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/components.xsd">

    <component id="mntl-affiliate-disclosure" ref="mntl-block">
        <info>
            <category>Mantle Components/Widgets</category>
            <displayName>Affiliate Disclosure</displayName>
            <description>Affiliate disclosure statement for legal.</description>
            <documentation>
				Adds Affiliate Disclosure tooltip and label/icon. This component includes a mntl-text-block for the label of the tooltip and a mntl-block for the tooltip icon.

				### Dependencies

				- __mntl-affiliate-disclosure\__text.text__ 

				Text for tooltip label

				- __mntl-affiliate-disclosure\__icon.mntl-svg.more-info__ 

				SVG for the tooltip icon

				- __mntl-affiliate-disclosure\__icon.attrs.data-tooltip__ 

				Disclosure text for the tooltip
			</documentation>
			
			<property name="arbitraryDependency" mode="remove" />
        </info>
        
        <stylesheet path="/static/mantle/components/widgets/affiliate-disclosure/affiliate-disclosure.css" />
        
        <!-- Only show affiliate disclosure when commerce disclosure does not appear and the affiliate flag is true -->
        <property name="arbitraryDependency" value="${((@document == null OR !(@document.revenueGroup == 'COMMERCE' OR @document.revenueGroup == 'PERFORMANCEMARKETING' OR @document.revenueGroup == 'COMMERCENEWSDEALS'))
        	AND (@document?.disclaimer?.affiliate ?: false)) ? 'true' : null}" onError="collapseSilent">
        	<model name="DOCUMENT" id="document" />
        </property>
        
		<component ref="mntl-tooltip" />
		<component id="mntl-affiliate-disclosure__text" location="content" ref="mntl-text-block">
			<map id="attrs">
				<property name="data-tooltip-trigger" value="true" />
			</map>
			<property name="text" value="Product Disclosure" />
			<property name="tag" value="span" />
		</component>
		
		<component id="mntl-affiliate-disclosure__icon" location="content" ref="mntl-block">
			<component location="content" ref="mntl-svg">
				<svg id="more-info" path="/static/mantle/svg/icon-more-info.svg" />
				<property name="name" value="more-info" />
			</component>
			<map id="attrs">
				<property name="data-tooltip" value="When you buy through links on our site, we may earn a commission." />
			</map>	
			<property name="tag" value="span" />
		</component>
		
    </component>

</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/widgets/article-feedback/article-feedback.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/components.xsd">

    <component id="mntl-article-feedback" resourcePath="/components/widgets/article-feedback/article-feedback.ftl">
        <info>
            <category>Mantle Components/Widgets</category>
            <displayName>Article Feedback</displayName>
            <description>Allows user to leave a rating (thumbs up/down) and comment on articles.</description>
            <documentation>
                ### **rating-section** location

                Used for the thumb rating buttons. Requires the class **js-rating-button** to trigger a rating on click.

                Buttons meant to leave a thumbs-up rating require the data attribute **data-thumbs-signal="THUMBS_UP"**.

                A thumbs-up rating will display the **success-section**. A thumbs-down rating will display the **feedback-section**.

                ### **success-section** location

                Shown after a rating is submitted.

                ### **feedback-section** location

                Shown after a rating button with the class **js-rating-button**, and without the data attribute **data-thumbs-signal="THUMBS_UP"** is clicked.

                Includes an **Other** button by default, which opens a text form on click. Requires the class **js-open-form-button** to trigger form opening.

                Used to include any other feedback buttons. Requires the class **js-submit-feedback-button** to submit the rating. The **succcess-section** will be shown
                after clicking a feedback button, or submitting the text form.
            </documentation>

            <property name="docId" value="2000278" type="integer" mode="replace" />

            <component location="rating-section" ref="mntl-button" id="thumbs-up-button">
                <property name="text" value="Yes!" />
                <property name="attrs" value="${{'data-thumbs-signal': 'THUMBS_UP'}}" />
            </component>
            <component location="rating-section" ref="mntl-button" id="thumbs-down-button">
                <property name="text" value="No" />
            </component>
            <component location="feedback-section" ref="mntl-button" id="not-enough-details-button">
                <property name="text" value="Not enough details" />
            </component>
            <component location="feedback-section" ref="mntl-button" id="wrong-article-button">
                <property name="text" value="Wrong article" />
            </component>
            <for id="thumbs-up-button, thumbs-down-button">
                <list id="class">
                    <property name="article-feedback__rating-button" value="article-feedback__rating-button" />
                    <property name="js-rating-button" value="js-rating-button" />
                </list>
            </for>
            <for id="not-enough-details-button, wrong-article-button">
                <list id="class">
                    <property name="article-feedback__feedback-button" value="article-feedback__feedback-button" />
                    <property name="js-submit-feedback" value="js-submit-feedback" />
                </list>
            </for>
        </info>

        <script path="/static/mantle/components/widgets/article-feedback/article-feedback.js" />

        <component location="feedback-section" ref="mntl-button" id="article-feedback__open-form-button">
            <property name="text" value="Other" />
            <list id="class">
                <property name="article-feedback__feedback-button" value="article-feedback__feedback-button" />
                <property name="js-open-form-button" value="js-open-form-button" />
            </list>
        </component>

        <component location="submit-button" ref="mntl-button" id="article-feedback__submit-button">
            <property name="text" value="Submit" />
        </component>

        <property name="docId" value="${requestContext.urlData.docId}" />
        <property name="ratingSectionHeading" value="Was this page helpful?" />
        <property name="successSectionHeading" value="Thanks for letting us know!" />
        <property name="feedbackSectionHeading" value="Tell us why!" />
        <property name="placeholderText" value="Tell us more..." />
    </component>

</components>

=== Adish786/Maintel/mantle-resources/src/main/resources/components/widgets/ad-table/ad-table.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/components.xsd">

    <!-- Ad Tables -->
    <component id="mntl-ad-table" ref="mntl-block">
        <info>
            <category>Mantle Components/Widgets</category>
            <displayName>Ad Table</displayName>
            <description>
                Displays a table of performance marketing ad creatives, usually ads specifically targetted to a particular intent-driven
                taxonomy or page type.
            </description>
            <documentation>
                This component references **mntl-ad-table-column**. When implementing on your vertical, it you must configure these ad 
                slots by passing in the correct id and pos value to each slot. 
            </documentation>
            <tags>In Progress</tags>
            
            <for id="mntl-ad-table__heading">
                <property name="text" value="Compare Popular Online Brokers" mode="replace" />
            </for>

            <for id="mntl-ad-table-column.gptAd.id, mntl-ad-table-column.gptAd.pos">
                <property name="tableType" value="brokertable" />
            </for>
        </info>

        <stylesheet path="/static/mantle/components/widgets/ad-table/css/ad-table.css" />
        <script path="/static/mantle/components/widgets/ad-table/js/ad-table.js" />

        <for id="id, pos">
            <property name="tableType" value="adtable" />
        </for>

        <component location="content" id="mntl-ad-table__heading" ref="mntl-text-block">
            <property name="text" value="Generic Ad Table Heading" />
        </component>

        <component location="content" id="mntl-ad-table__disclosure" ref="mntl-block">
            <property name="trackingContainer" value="true" type="boolean" />

            <component location="content" id="mntl-ad-table__disclosure-label" ref="mntl-button">
                <property name="text" value="Advertiser Disclosure" />
            </component>

            <component location="content" id="mntl-ad-table__disclosure-description" ref="mntl-block">
                <component location="content" id="mntl-ad-table__disclosure-close" ref="mntl-text-block">
                    <property name="text" value="&amp;times;" />
                </component>

                <component location="content" id="mntl-ad-table__disclosure-content" ref="mntl-text-block">
                    <property name="text" value="The offers that appear in this table are from partnerships from which Dotdash receives compensation." />
                </component>
            </component>
        </component> <!-- /mntl-ad-table__disclosure -->

        <component location="content" id="mntl-ad-table__content" ref="mntl-block">
            <component location="content" id="mntl-ad-table__headers" ref="mntl-block">
                <component location="content" id="mntl-ad-table__heading-1" ref="mntl-text-block">
                    <property name="text" value="Provider" />
                </component>

                <component location="content" id="mntl-ad-table__heading-2" ref="mntl-text-block">
                    <property name="text" value="Name" />
                </component>

                <component location="content" id="mntl-ad-table__heading-3" ref="mntl-text-block">
                    <property name="text" value="Description" />
                </component>
            </component>

            <component location="content" ref="mntl-ad-table-column" >
                <for id="gptAd">
                    <property name="id" value="${@tableType}1" />
                    <property name="pos" value="${@tableType}1"  />
                </for>
            </component>

            <component location="content" ref="mntl-ad-table-column" >
                <for id="gptAd">
                    <property name="id" value="${@tableType}2" />
                    <property name="pos" value="${@tableType}2"  />
                </for>
            </component>

            <component location="content" ref="mntl-ad-table-column" views="pc, tablet" >
                <for id="gptAd">
                    <property name="id" value="${@tableType}3" />
                    <property name="pos" value="${@tableType}3"  />
                </for>
            </component>
        </component> <!-- /mntl-ad-table__content -->

    </component> <!-- /mntl-ad-table -->

    <component id="mntl-ad-table--vertical" ref="mntl-ad-table" >
        <for id="mntl-ad-table__heading-1">
            <property name="text" value="Lender" mode="replace" />
        </for>
        
        <for id="mntl-ad-table__heading-2">
            <property name="text" value="At A Glance" mode="replace" />
        </for>
    </component>
</components>
